//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisEnthusiasts.Models
{
    using System;
    using System.Collections.Generic;
    
    //Grand Slam class (For your db reference: Double click Tennis.MDF file inside "App_Data" and view table "GrandSlam"
    public partial class GrandSlam
    {
        public int Id { get; set; }
        public string Winner { get; set; }
        public string RunnerUp { get; set; }
        public string Title { get; set; }
        public System.DateTime TriumphDate { get; set; }
    }
}
